apiVersion: v1
kind: Pod
metadata:
  name: rmfakecloud-builder
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  volumes:
  - name: kaniko-secret
    secret:
      secretName: jenkins-regcred
      items:
      - key: .dockerconfigjson
        path: config.json